export const primitiveColors = {
  transparent: 'transparent',
  white: '#FFFFFF',
  black: '#000000',
  plum: {
    100: '#EEE5F7',
    200: '#DCC9EC',
    600: '#6C3AA8',
    700: '#5B2A86',
    800: '#4B1F6F',
    900: '#35144F',
  },
  terracotta: {
    100: '#F8E8E1',
    200: '#EDC4B4',
    600: '#A64B2A',
    700: '#8A3B22',
  },
  gold: {
    200: '#F1D59A',
    700: '#8A4A00',
  },
  ivory: {
    50: '#FFF9F5',
  },
  sand: {
    100: '#F5EEE8',
  },
  ink: {
    500: '#667085',
    700: '#475467',
    950: '#1D1B20',
  },
  border: {
    200: '#E4DAD3',
  },
  success: {
    700: '#1F6F4A',
  },
  warning: {
    700: '#8A4A00',
  },
  danger: {
    700: '#B42318',
  },
  info: {
    700: '#245B8A',
  },
} as const;

export const semanticColorNames = [
  'background',
  'backgroundSubtle',
  'surface',
  'surfaceRaised',
  'surfaceInverse',
  'textPrimary',
  'textSecondary',
  'textTertiary',
  'textInverse',
  'border',
  'borderStrong',
  'primary',
  'primaryPressed',
  'primarySoft',
  'onPrimary',
  'accent',
  'accentPressed',
  'accentSoft',
  'onAccent',
  'success',
  'successSoft',
  'warning',
  'warningSoft',
  'danger',
  'dangerSoft',
  'info',
  'infoSoft',
  'focusRing',
  'scrim',
  'skeletonBase',
  'skeletonHighlight',
] as const;

export type SemanticColorName = (typeof semanticColorNames)[number];
export type SemanticColorTheme = Readonly<Record<SemanticColorName, string>>;

export const lightColorTheme = {
  background: primitiveColors.ivory[50],
  backgroundSubtle: primitiveColors.sand[100],
  surface: primitiveColors.white,
  surfaceRaised: primitiveColors.white,
  surfaceInverse: primitiveColors.ink[950],
  textPrimary: primitiveColors.ink[950],
  textSecondary: primitiveColors.ink[700],
  textTertiary: primitiveColors.ink[500],
  textInverse: primitiveColors.white,
  border: primitiveColors.border[200],
  borderStrong: '#C6B8AE',
  primary: primitiveColors.plum[600],
  primaryPressed: primitiveColors.plum[800],
  primarySoft: primitiveColors.plum[100],
  onPrimary: primitiveColors.white,
  accent: primitiveColors.terracotta[600],
  accentPressed: primitiveColors.terracotta[700],
  accentSoft: primitiveColors.terracotta[100],
  onAccent: primitiveColors.white,
  success: primitiveColors.success[700],
  successSoft: '#E2F3E9',
  warning: primitiveColors.warning[700],
  warningSoft: '#FFF1CF',
  danger: primitiveColors.danger[700],
  dangerSoft: '#FDE8E7',
  info: primitiveColors.info[700],
  infoSoft: '#E7F1F8',
  focusRing: primitiveColors.plum[600],
  scrim: 'rgba(0, 0, 0, 0.52)',
  skeletonBase: '#E9E1DC',
  skeletonHighlight: '#F8F3EF',
} as const satisfies SemanticColorTheme;

export const darkColorTheme = {
  background: '#18131B',
  backgroundSubtle: '#211924',
  surface: '#2B2130',
  surfaceRaised: '#35283B',
  surfaceInverse: primitiveColors.ivory[50],
  textPrimary: primitiveColors.ivory[50],
  textSecondary: '#D8CEDC',
  textTertiary: '#B8ACBD',
  textInverse: primitiveColors.ink[950],
  border: '#4A3A50',
  borderStrong: '#68536F',
  primary: '#C9A7E6',
  primaryPressed: '#B488D8',
  primarySoft: '#3E2A4A',
  onPrimary: primitiveColors.ink[950],
  accent: '#E6A88D',
  accentPressed: '#D68F70',
  accentSoft: '#4B2D27',
  onAccent: primitiveColors.ink[950],
  success: '#79C99E',
  successSoft: '#1F3D2E',
  warning: '#F1C56C',
  warningSoft: '#493819',
  danger: '#F29A92',
  dangerSoft: '#4B2527',
  info: '#8FC4E8',
  infoSoft: '#20394A',
  focusRing: primitiveColors.plum[200],
  scrim: 'rgba(0, 0, 0, 0.64)',
  skeletonBase: '#3B2F40',
  skeletonHighlight: '#4A3B50',
} as const satisfies SemanticColorTheme;

export const colorThemes = {
  light: lightColorTheme,
  dark: darkColorTheme,
} as const;

export type ColorThemeName = keyof typeof colorThemes;
