-- Vastra Supabase schema starter
-- Generated for PostgreSQL/Supabase. Review in local and staging environments before production.
-- All money values are BIGINT paise; timestamps are TIMESTAMPTZ; geospatial fields use PostGIS.


-- Enable RLS on every exposed public table. No policy means deny-by-default.

alter table public."profiles" enable row level security;
alter table public."profiles" force row level security;
alter table public."user_devices" enable row level security;
alter table public."user_devices" force row level security;
alter table public."addresses" enable row level security;
alter table public."addresses" force row level security;
alter table public."customer_profiles" enable row level security;
alter table public."customer_profiles" force row level security;
alter table public."customer_preferences" enable row level security;
alter table public."customer_preferences" force row level security;
alter table public."merchant_profiles" enable row level security;
alter table public."merchant_profiles" force row level security;
alter table public."captain_profiles" enable row level security;
alter table public."captain_profiles" force row level security;
alter table public."admin_profiles" enable row level security;
alter table public."admin_profiles" force row level security;
alter table public."roles" enable row level security;
alter table public."roles" force row level security;
alter table public."permissions" enable row level security;
alter table public."permissions" force row level security;
alter table public."user_roles" enable row level security;
alter table public."user_roles" force row level security;
alter table public."role_permissions" enable row level security;
alter table public."role_permissions" force row level security;
alter table public."shops" enable row level security;
alter table public."shops" force row level security;
alter table public."shop_hours" enable row level security;
alter table public."shop_hours" force row level security;
alter table public."shop_documents" enable row level security;
alter table public."shop_documents" force row level security;
alter table public."shop_bank_accounts" enable row level security;
alter table public."shop_bank_accounts" force row level security;
alter table public."categories" enable row level security;
alter table public."categories" force row level security;
alter table public."products" enable row level security;
alter table public."products" force row level security;
alter table public."product_images" enable row level security;
alter table public."product_images" force row level security;
alter table public."product_variants" enable row level security;
alter table public."product_variants" force row level security;
alter table public."variant_barcodes" enable row level security;
alter table public."variant_barcodes" force row level security;
alter table public."inventory_balances" enable row level security;
alter table public."inventory_balances" force row level security;
alter table public."inventory_movements" enable row level security;
alter table public."inventory_movements" force row level security;
alter table public."inventory_reservations" enable row level security;
alter table public."inventory_reservations" force row level security;
alter table public."product_photo_matches" enable row level security;
alter table public."product_photo_matches" force row level security;
alter table public."shop_favourites" enable row level security;
alter table public."shop_favourites" force row level security;
alter table public."wishlist_items" enable row level security;
alter table public."wishlist_items" force row level security;
alter table public."shop_collections" enable row level security;
alter table public."shop_collections" force row level security;
alter table public."shop_collection_items" enable row level security;
alter table public."shop_collection_items" force row level security;
alter table public."offers" enable row level security;
alter table public."offers" force row level security;
alter table public."offer_products" enable row level security;
alter table public."offer_products" force row level security;
alter table public."offer_redemptions" enable row level security;
alter table public."offer_redemptions" force row level security;
alter table public."offline_sales" enable row level security;
alter table public."offline_sales" force row level security;
alter table public."offline_sale_items" enable row level security;
alter table public."offline_sale_items" force row level security;
alter table public."carts" enable row level security;
alter table public."carts" force row level security;
alter table public."cart_items" enable row level security;
alter table public."cart_items" force row level security;
alter table public."orders" enable row level security;
alter table public."orders" force row level security;
alter table public."order_items" enable row level security;
alter table public."order_items" force row level security;
alter table public."order_status_history" enable row level security;
alter table public."order_status_history" force row level security;
alter table public."merchant_order_alerts" enable row level security;
alter table public."merchant_order_alerts" force row level security;
alter table public."merchant_order_issues" enable row level security;
alter table public."merchant_order_issues" force row level security;
alter table public."order_item_verifications" enable row level security;
alter table public."order_item_verifications" force row level security;
alter table public."payments" enable row level security;
alter table public."payments" force row level security;
alter table public."payment_events" enable row level security;
alter table public."payment_events" force row level security;
alter table public."return_requests" enable row level security;
alter table public."return_requests" force row level security;
alter table public."return_items" enable row level security;
alter table public."return_items" force row level security;
alter table public."return_evidence" enable row level security;
alter table public."return_evidence" force row level security;
alter table public."return_status_history" enable row level security;
alter table public."return_status_history" force row level security;
alter table public."refunds" enable row level security;
alter table public."refunds" force row level security;
alter table public."merchant_settlements" enable row level security;
alter table public."merchant_settlements" force row level security;
alter table public."merchant_settlement_items" enable row level security;
alter table public."merchant_settlement_items" force row level security;
alter table public."captain_documents" enable row level security;
alter table public."captain_documents" force row level security;
alter table public."delivery_tasks" enable row level security;
alter table public."delivery_tasks" force row level security;
alter table public."delivery_assignments" enable row level security;
alter table public."delivery_assignments" force row level security;
alter table public."captain_current_locations" enable row level security;
alter table public."captain_current_locations" force row level security;
alter table public."captain_location_history" enable row level security;
alter table public."captain_location_history" force row level security;
alter table public."delivery_events" enable row level security;
alter table public."delivery_events" force row level security;
alter table public."cod_collections" enable row level security;
alter table public."cod_collections" force row level security;
alter table public."captain_earnings" enable row level security;
alter table public."captain_earnings" force row level security;
alter table public."captain_payouts" enable row level security;
alter table public."captain_payouts" force row level security;
alter table public."captain_payout_items" enable row level security;
alter table public."captain_payout_items" force row level security;
alter table public."style_groups" enable row level security;
alter table public."style_groups" force row level security;
alter table public."style_group_members" enable row level security;
alter table public."style_group_members" force row level security;
alter table public."style_group_member_preferences" enable row level security;
alter table public."style_group_member_preferences" force row level security;
alter table public."style_themes" enable row level security;
alter table public."style_themes" force row level security;
alter table public."style_polls" enable row level security;
alter table public."style_polls" force row level security;
alter table public."style_poll_options" enable row level security;
alter table public."style_poll_options" force row level security;
alter table public."style_poll_votes" enable row level security;
alter table public."style_poll_votes" force row level security;
alter table public."style_moodboards" enable row level security;
alter table public."style_moodboards" force row level security;
alter table public."style_moodboard_items" enable row level security;
alter table public."style_moodboard_items" force row level security;
alter table public."notifications" enable row level security;
alter table public."notifications" force row level security;
alter table public."notification_deliveries" enable row level security;
alter table public."notification_deliveries" force row level security;
alter table public."notification_preferences" enable row level security;
alter table public."notification_preferences" force row level security;
alter table public."reviews" enable row level security;
alter table public."reviews" force row level security;
alter table public."customer_events" enable row level security;
alter table public."customer_events" force row level security;
alter table public."recommendation_sets" enable row level security;
alter table public."recommendation_sets" force row level security;
alter table public."recommendation_items" enable row level security;
alter table public."recommendation_items" force row level security;
alter table public."product_embeddings" enable row level security;
alter table public."product_embeddings" force row level security;
alter table public."customer_embeddings" enable row level security;
alter table public."customer_embeddings" force row level security;
alter table public."size_charts" enable row level security;
alter table public."size_charts" force row level security;
alter table public."size_chart_measurements" enable row level security;
alter table public."size_chart_measurements" force row level security;
alter table public."customer_body_profiles" enable row level security;
alter table public."customer_body_profiles" force row level security;
alter table public."body_measurements" enable row level security;
alter table public."body_measurements" force row level security;
alter table public."body_scan_sessions" enable row level security;
alter table public."body_scan_sessions" force row level security;
alter table public."fit_recommendations" enable row level security;
alter table public."fit_recommendations" force row level security;
alter table public."fit_feedback" enable row level security;
alter table public."fit_feedback" force row level security;
alter table public."virtual_tryon_sessions" enable row level security;
alter table public."virtual_tryon_sessions" force row level security;
alter table public."virtual_tryon_outputs" enable row level security;
alter table public."virtual_tryon_outputs" force row level security;
alter table public."style_recommendation_sets" enable row level security;
alter table public."style_recommendation_sets" force row level security;
alter table public."style_recommendation_items" enable row level security;
alter table public."style_recommendation_items" force row level security;
alter table public."support_tickets" enable row level security;
alter table public."support_tickets" force row level security;
alter table public."support_messages" enable row level security;
alter table public."support_messages" force row level security;
alter table public."campaigns" enable row level security;
alter table public."campaigns" force row level security;
alter table public."banners" enable row level security;
alter table public."banners" force row level security;
alter table public."merchant_leads" enable row level security;
alter table public."merchant_leads" force row level security;
alter table public."field_visits" enable row level security;
alter table public."field_visits" force row level security;
alter table public."field_visit_checklist_items" enable row level security;
alter table public."field_visit_checklist_items" force row level security;
alter table public."product_moderation_cases" enable row level security;
alter table public."product_moderation_cases" force row level security;
alter table public."approval_requests" enable row level security;
alter table public."approval_requests" force row level security;
alter table public."fraud_cases" enable row level security;
alter table public."fraud_cases" force row level security;
alter table public."audit_logs" enable row level security;
alter table public."audit_logs" force row level security;
alter table public."system_settings" enable row level security;
alter table public."system_settings" force row level security;
alter table public."service_zones" enable row level security;
alter table public."service_zones" force row level security;

-- Basic grants: policies still decide which rows are accessible.

grant select, insert, update, delete on public."profiles" to authenticated;
grant select, insert, update, delete on public."user_devices" to authenticated;
grant select, insert, update, delete on public."addresses" to authenticated;
grant select, insert, update, delete on public."customer_profiles" to authenticated;
grant select, insert, update, delete on public."customer_preferences" to authenticated;
grant select, insert, update, delete on public."merchant_profiles" to authenticated;
grant select, insert, update, delete on public."captain_profiles" to authenticated;
grant select, insert, update, delete on public."admin_profiles" to authenticated;
grant select, insert, update, delete on public."roles" to authenticated;
grant select, insert, update, delete on public."permissions" to authenticated;
grant select, insert, update, delete on public."user_roles" to authenticated;
grant select, insert, update, delete on public."role_permissions" to authenticated;
grant select, insert, update, delete on public."shops" to authenticated;
grant select, insert, update, delete on public."shop_hours" to authenticated;
grant select, insert, update, delete on public."shop_documents" to authenticated;
grant select, insert, update, delete on public."shop_bank_accounts" to authenticated;
grant select, insert, update, delete on public."categories" to authenticated;
grant select, insert, update, delete on public."products" to authenticated;
grant select, insert, update, delete on public."product_images" to authenticated;
grant select, insert, update, delete on public."product_variants" to authenticated;
grant select, insert, update, delete on public."variant_barcodes" to authenticated;
grant select, insert, update, delete on public."inventory_balances" to authenticated;
grant select, insert, update, delete on public."inventory_movements" to authenticated;
grant select, insert, update, delete on public."inventory_reservations" to authenticated;
grant select, insert, update, delete on public."product_photo_matches" to authenticated;
grant select, insert, update, delete on public."shop_favourites" to authenticated;
grant select, insert, update, delete on public."wishlist_items" to authenticated;
grant select, insert, update, delete on public."shop_collections" to authenticated;
grant select, insert, update, delete on public."shop_collection_items" to authenticated;
grant select, insert, update, delete on public."offers" to authenticated;
grant select, insert, update, delete on public."offer_products" to authenticated;
grant select, insert, update, delete on public."offer_redemptions" to authenticated;
grant select, insert, update, delete on public."offline_sales" to authenticated;
grant select, insert, update, delete on public."offline_sale_items" to authenticated;
grant select, insert, update, delete on public."carts" to authenticated;
grant select, insert, update, delete on public."cart_items" to authenticated;
grant select, insert, update, delete on public."orders" to authenticated;
grant select, insert, update, delete on public."order_items" to authenticated;
grant select, insert, update, delete on public."order_status_history" to authenticated;
grant select, insert, update, delete on public."merchant_order_alerts" to authenticated;
grant select, insert, update, delete on public."merchant_order_issues" to authenticated;
grant select, insert, update, delete on public."order_item_verifications" to authenticated;
grant select, insert, update, delete on public."payments" to authenticated;
grant select, insert, update, delete on public."payment_events" to authenticated;
grant select, insert, update, delete on public."return_requests" to authenticated;
grant select, insert, update, delete on public."return_items" to authenticated;
grant select, insert, update, delete on public."return_evidence" to authenticated;
grant select, insert, update, delete on public."return_status_history" to authenticated;
grant select, insert, update, delete on public."refunds" to authenticated;
grant select, insert, update, delete on public."merchant_settlements" to authenticated;
grant select, insert, update, delete on public."merchant_settlement_items" to authenticated;
grant select, insert, update, delete on public."captain_documents" to authenticated;
grant select, insert, update, delete on public."delivery_tasks" to authenticated;
grant select, insert, update, delete on public."delivery_assignments" to authenticated;
grant select, insert, update, delete on public."captain_current_locations" to authenticated;
grant select, insert, update, delete on public."captain_location_history" to authenticated;
grant select, insert, update, delete on public."delivery_events" to authenticated;
grant select, insert, update, delete on public."cod_collections" to authenticated;
grant select, insert, update, delete on public."captain_earnings" to authenticated;
grant select, insert, update, delete on public."captain_payouts" to authenticated;
grant select, insert, update, delete on public."captain_payout_items" to authenticated;
grant select, insert, update, delete on public."style_groups" to authenticated;
grant select, insert, update, delete on public."style_group_members" to authenticated;
grant select, insert, update, delete on public."style_group_member_preferences" to authenticated;
grant select, insert, update, delete on public."style_themes" to authenticated;
grant select, insert, update, delete on public."style_polls" to authenticated;
grant select, insert, update, delete on public."style_poll_options" to authenticated;
grant select, insert, update, delete on public."style_poll_votes" to authenticated;
grant select, insert, update, delete on public."style_moodboards" to authenticated;
grant select, insert, update, delete on public."style_moodboard_items" to authenticated;
grant select, insert, update, delete on public."notifications" to authenticated;
grant select, insert, update, delete on public."notification_deliveries" to authenticated;
grant select, insert, update, delete on public."notification_preferences" to authenticated;
grant select, insert, update, delete on public."reviews" to authenticated;
grant select, insert, update, delete on public."customer_events" to authenticated;
grant select, insert, update, delete on public."recommendation_sets" to authenticated;
grant select, insert, update, delete on public."recommendation_items" to authenticated;
grant select, insert, update, delete on public."product_embeddings" to authenticated;
grant select, insert, update, delete on public."customer_embeddings" to authenticated;
grant select, insert, update, delete on public."size_charts" to authenticated;
grant select, insert, update, delete on public."size_chart_measurements" to authenticated;
grant select, insert, update, delete on public."customer_body_profiles" to authenticated;
grant select, insert, update, delete on public."body_measurements" to authenticated;
grant select, insert, update, delete on public."body_scan_sessions" to authenticated;
grant select, insert, update, delete on public."fit_recommendations" to authenticated;
grant select, insert, update, delete on public."fit_feedback" to authenticated;
grant select, insert, update, delete on public."virtual_tryon_sessions" to authenticated;
grant select, insert, update, delete on public."virtual_tryon_outputs" to authenticated;
grant select, insert, update, delete on public."style_recommendation_sets" to authenticated;
grant select, insert, update, delete on public."style_recommendation_items" to authenticated;
grant select, insert, update, delete on public."support_tickets" to authenticated;
grant select, insert, update, delete on public."support_messages" to authenticated;
grant select, insert, update, delete on public."campaigns" to authenticated;
grant select, insert, update, delete on public."banners" to authenticated;
grant select, insert, update, delete on public."merchant_leads" to authenticated;
grant select, insert, update, delete on public."field_visits" to authenticated;
grant select, insert, update, delete on public."field_visit_checklist_items" to authenticated;
grant select, insert, update, delete on public."product_moderation_cases" to authenticated;
grant select, insert, update, delete on public."approval_requests" to authenticated;
grant select, insert, update, delete on public."fraud_cases" to authenticated;
grant select, insert, update, delete on public."audit_logs" to authenticated;
grant select, insert, update, delete on public."system_settings" to authenticated;
grant select, insert, update, delete on public."service_zones" to authenticated;
grant select on public."shops" to anon;
create policy "shops_public_read" on public."shops" for select to anon, authenticated using (deleted_at is null and verification_status = 'VERIFIED' and operational_status not in ('SUSPENDED','PAUSED'));
grant select on public."shop_hours" to anon;
create policy "shop_hours_public_read" on public."shop_hours" for select to anon, authenticated using (true);
grant select on public."categories" to anon;
create policy "categories_public_read" on public."categories" for select to anon, authenticated using (true);
grant select on public."products" to anon;
create policy "products_public_read" on public."products" for select to anon, authenticated using (deleted_at is null and is_active and moderation_status = 'APPROVED');
grant select on public."product_images" to anon;
create policy "product_images_public_read" on public."product_images" for select to anon, authenticated using (true);
grant select on public."product_variants" to anon;
create policy "product_variants_public_read" on public."product_variants" for select to anon, authenticated using (is_active);
grant select on public."variant_barcodes" to anon;
create policy "variant_barcodes_public_read" on public."variant_barcodes" for select to anon, authenticated using (true);
grant select on public."shop_collections" to anon;
create policy "shop_collections_public_read" on public."shop_collections" for select to anon, authenticated using (true);
grant select on public."shop_collection_items" to anon;
create policy "shop_collection_items_public_read" on public."shop_collection_items" for select to anon, authenticated using (true);
grant select on public."offers" to anon;
create policy "offers_public_read" on public."offers" for select to anon, authenticated using (status = 'ACTIVE' and now() between starts_at and ends_at);
grant select on public."offer_products" to anon;
create policy "offer_products_public_read" on public."offer_products" for select to anon, authenticated using (true);
grant select on public."reviews" to anon;
create policy "reviews_public_read" on public."reviews" for select to anon, authenticated using (true);
grant select on public."service_zones" to anon;
create policy "service_zones_public_read" on public."service_zones" for select to anon, authenticated using (true);
grant select on public."banners" to anon;
create policy "banners_public_read" on public."banners" for select to anon, authenticated using (true);
grant select on public."campaigns" to anon;
create policy "campaigns_public_read" on public."campaigns" for select to anon, authenticated using (status = 'ACTIVE' and now() between starts_at and ends_at);
create policy "profiles_read_self" on public."profiles" for select to authenticated using (id = (select auth.uid()));
create policy "profiles_update_self" on public."profiles" for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "devices_self" on public."user_devices" for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "addresses_self" on public."addresses" for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "customer_profile_self" on public."customer_profiles" for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "customer_preferences_self" on public."customer_preferences" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "notification_preferences_self" on public."notification_preferences" for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "notifications_self_read" on public."notifications" for select to authenticated using (user_id = (select auth.uid()));
create policy "notifications_self_update" on public."notifications" for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "shops_merchant_read" on public."shops" for select to authenticated using ((select private.owns_shop(id)));
create policy "shops_merchant_write" on public."shops" for all to authenticated using ((select private.owns_shop(id))) with check ((select private.owns_shop(id)));
create policy "shop_hours_merchant_read" on public."shop_hours" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "shop_hours_merchant_write" on public."shop_hours" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "shop_documents_merchant_read" on public."shop_documents" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "shop_documents_merchant_write" on public."shop_documents" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "shop_bank_accounts_merchant_read" on public."shop_bank_accounts" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "shop_bank_accounts_merchant_write" on public."shop_bank_accounts" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "products_merchant_read" on public."products" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "products_merchant_write" on public."products" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "product_variants_merchant_read" on public."product_variants" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "product_variants_merchant_write" on public."product_variants" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "inventory_balances_merchant_read" on public."inventory_balances" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "inventory_balances_merchant_write" on public."inventory_balances" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "inventory_movements_merchant_read" on public."inventory_movements" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "inventory_reservations_merchant_read" on public."inventory_reservations" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "inventory_reservations_merchant_write" on public."inventory_reservations" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "product_photo_matches_merchant_read" on public."product_photo_matches" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "product_photo_matches_merchant_write" on public."product_photo_matches" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "shop_collections_merchant_read" on public."shop_collections" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "shop_collections_merchant_write" on public."shop_collections" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "offers_merchant_read" on public."offers" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "offers_merchant_write" on public."offers" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "offline_sales_merchant_read" on public."offline_sales" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "offline_sales_merchant_write" on public."offline_sales" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "orders_merchant_read" on public."orders" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "orders_merchant_write" on public."orders" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "merchant_order_alerts_merchant_read" on public."merchant_order_alerts" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "merchant_order_alerts_merchant_write" on public."merchant_order_alerts" for all to authenticated using ((select private.owns_shop(shop_id))) with check ((select private.owns_shop(shop_id)));
create policy "merchant_settlements_merchant_read" on public."merchant_settlements" for select to authenticated using ((select private.owns_shop(shop_id)));
create policy "product_images_merchant_access" on public."product_images" for all to authenticated using (exists (select 1 from public.products p where p.id = product_id and private.owns_shop(p.shop_id))) with check (exists (select 1 from public.products p where p.id = product_id and private.owns_shop(p.shop_id)));
create policy "variant_barcodes_merchant_access" on public."variant_barcodes" for all to authenticated using (exists (select 1 from public.product_variants v where v.id = variant_id and private.owns_shop(v.shop_id))) with check (exists (select 1 from public.product_variants v where v.id = variant_id and private.owns_shop(v.shop_id)));
create policy "shop_collection_items_merchant_access" on public."shop_collection_items" for all to authenticated using (exists (select 1 from public.shop_collections c where c.id = collection_id and private.owns_shop(c.shop_id))) with check (exists (select 1 from public.shop_collections c where c.id = collection_id and private.owns_shop(c.shop_id)));
create policy "offer_products_merchant_access" on public."offer_products" for all to authenticated using (exists (select 1 from public.offers o where o.id = offer_id and private.owns_shop(o.shop_id))) with check (exists (select 1 from public.offers o where o.id = offer_id and private.owns_shop(o.shop_id)));
create policy "offline_sale_items_merchant_access" on public."offline_sale_items" for all to authenticated using (exists (select 1 from public.offline_sales s where s.id = offline_sale_id and private.owns_shop(s.shop_id))) with check (exists (select 1 from public.offline_sales s where s.id = offline_sale_id and private.owns_shop(s.shop_id)));
create policy "order_items_merchant_access" on public."order_items" for all to authenticated using (exists (select 1 from public.orders o where o.id = order_id and private.owns_shop(o.shop_id))) with check (exists (select 1 from public.orders o where o.id = order_id and private.owns_shop(o.shop_id)));
create policy "merchant_order_issues_merchant_access" on public."merchant_order_issues" for all to authenticated using (exists (select 1 from public.orders o where o.id = order_id and private.owns_shop(o.shop_id))) with check (exists (select 1 from public.orders o where o.id = order_id and private.owns_shop(o.shop_id)));
create policy "order_item_verifications_merchant_access" on public."order_item_verifications" for all to authenticated using (exists (select 1 from public.order_items oi join public.orders o on o.id=oi.order_id where oi.id=order_item_id and private.owns_shop(o.shop_id))) with check (exists (select 1 from public.order_items oi join public.orders o on o.id=oi.order_id where oi.id=order_item_id and private.owns_shop(o.shop_id)));
create policy "return_requests_merchant_access" on public."return_requests" for all to authenticated using (private.owns_shop(shop_id)) with check (private.owns_shop(shop_id));
create policy "return_items_merchant_access" on public."return_items" for all to authenticated using (exists (select 1 from public.return_requests r where r.id=return_request_id and private.owns_shop(r.shop_id))) with check (exists (select 1 from public.return_requests r where r.id=return_request_id and private.owns_shop(r.shop_id)));
create policy "return_evidence_merchant_access" on public."return_evidence" for all to authenticated using (exists (select 1 from public.return_requests r where r.id=return_request_id and private.owns_shop(r.shop_id))) with check (exists (select 1 from public.return_requests r where r.id=return_request_id and private.owns_shop(r.shop_id)));
create policy "merchant_settlement_items_merchant_access" on public."merchant_settlement_items" for all to authenticated using (exists (select 1 from public.merchant_settlements s where s.id=settlement_id and private.owns_shop(s.shop_id))) with check (exists (select 1 from public.merchant_settlements s where s.id=settlement_id and private.owns_shop(s.shop_id)));
create policy "shop_favourites_customer_access" on public."shop_favourites" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "wishlist_items_customer_access" on public."wishlist_items" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "carts_customer_access" on public."carts" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "orders_customer_access" on public."orders" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "payments_customer_access" on public."payments" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "return_requests_customer_access" on public."return_requests" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "customer_events_customer_access" on public."customer_events" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "recommendation_sets_customer_access" on public."recommendation_sets" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "customer_body_profiles_customer_access" on public."customer_body_profiles" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "fit_recommendations_customer_access" on public."fit_recommendations" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "fit_feedback_customer_access" on public."fit_feedback" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "virtual_tryon_sessions_customer_access" on public."virtual_tryon_sessions" for all to authenticated using (customer_id = (select auth.uid())) with check (customer_id = (select auth.uid()));
create policy "cart_items_customer_access" on public."cart_items" for all to authenticated using (exists (select 1 from public.carts c where c.id=cart_id and c.customer_id=(select auth.uid()))) with check (exists (select 1 from public.carts c where c.id=cart_id and c.customer_id=(select auth.uid())));
create policy "order_items_customer_access" on public."order_items" for all to authenticated using (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid()))) with check (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid())));
create policy "order_status_history_customer_access" on public."order_status_history" for all to authenticated using (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid()))) with check (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid())));
create policy "payment_events_customer_access" on public."payment_events" for all to authenticated using (exists (select 1 from public.payments p where p.id=payment_id and p.customer_id=(select auth.uid()))) with check (exists (select 1 from public.payments p where p.id=payment_id and p.customer_id=(select auth.uid())));
create policy "refunds_customer_access" on public."refunds" for all to authenticated using (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid()))) with check (exists (select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid())));
create policy "return_items_customer_access" on public."return_items" for all to authenticated using (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid()))) with check (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid())));
create policy "return_evidence_customer_access" on public."return_evidence" for all to authenticated using (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid()))) with check (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid())));
create policy "return_status_history_customer_access" on public."return_status_history" for all to authenticated using (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid()))) with check (exists (select 1 from public.return_requests r where r.id=return_request_id and r.customer_id=(select auth.uid())));
create policy "recommendation_items_customer_access" on public."recommendation_items" for all to authenticated using (exists (select 1 from public.recommendation_sets rs where rs.id=recommendation_set_id and rs.customer_id=(select auth.uid()))) with check (exists (select 1 from public.recommendation_sets rs where rs.id=recommendation_set_id and rs.customer_id=(select auth.uid())));
create policy "body_measurements_customer_access" on public."body_measurements" for all to authenticated using (exists (select 1 from public.customer_body_profiles bp where bp.id=body_profile_id and bp.customer_id=(select auth.uid()))) with check (exists (select 1 from public.customer_body_profiles bp where bp.id=body_profile_id and bp.customer_id=(select auth.uid())));
create policy "body_scan_sessions_customer_access" on public."body_scan_sessions" for all to authenticated using (customer_id=(select auth.uid())) with check (customer_id=(select auth.uid()));
create policy "virtual_tryon_outputs_customer_access" on public."virtual_tryon_outputs" for all to authenticated using (exists (select 1 from public.virtual_tryon_sessions s where s.id=tryon_session_id and s.customer_id=(select auth.uid()))) with check (exists (select 1 from public.virtual_tryon_sessions s where s.id=tryon_session_id and s.customer_id=(select auth.uid())));
create policy "style_groups_member_read" on public."style_groups" for select to authenticated using (private.is_style_group_member(id));
create policy "style_groups_creator_write" on public."style_groups" for all to authenticated using (creator_customer_id=(select auth.uid())) with check (creator_customer_id=(select auth.uid()));
create policy "style_group_members_read" on public."style_group_members" for select to authenticated using (private.is_style_group_member(group_id));
create policy "style_group_members_write" on public."style_group_members" for all to authenticated using (private.is_style_group_member(group_id)) with check (private.is_style_group_member(group_id));
create policy "group_preferences_owner" on public."style_group_member_preferences" for all to authenticated using (exists (select 1 from public.style_group_members m where m.id=group_member_id and m.customer_id=(select auth.uid()))) with check (exists (select 1 from public.style_group_members m where m.id=group_member_id and m.customer_id=(select auth.uid())));
create policy "style_themes_group_access" on public."style_themes" for all to authenticated using (private.is_style_group_member(group_id)) with check (private.is_style_group_member(group_id));
create policy "style_polls_group_access" on public."style_polls" for all to authenticated using (private.is_style_group_member(group_id)) with check (private.is_style_group_member(group_id));
create policy "style_moodboards_group_access" on public."style_moodboards" for all to authenticated using (private.is_style_group_member(group_id)) with check (private.is_style_group_member(group_id));
create policy "style_recommendation_sets_group_access" on public."style_recommendation_sets" for all to authenticated using (private.is_style_group_member(group_id)) with check (private.is_style_group_member(group_id));
create policy "captain_profile_self" on public."captain_profiles" for select to authenticated using (user_id=(select auth.uid()));
create policy "captain_profile_self_update" on public."captain_profiles" for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "captain_documents_self" on public."captain_documents" for all to authenticated using (captain_id=(select auth.uid())) with check (captain_id=(select auth.uid()));
create policy "delivery_tasks_captain" on public."delivery_tasks" for select to authenticated using (assigned_captain_id=(select auth.uid()));
create policy "delivery_assignments_captain" on public."delivery_assignments" for select to authenticated using (captain_id=(select auth.uid()));
create policy "captain_location_self" on public."captain_current_locations" for all to authenticated using (captain_id=(select auth.uid())) with check (captain_id=(select auth.uid()));
create policy "captain_location_history_self_insert" on public."captain_location_history" for insert to authenticated with check (captain_id=(select auth.uid()));
create policy "delivery_events_captain" on public."delivery_events" for select to authenticated using (exists (select 1 from public.delivery_tasks d where d.id=delivery_task_id and d.assigned_captain_id=(select auth.uid())));
create policy "captain_earnings_self" on public."captain_earnings" for select to authenticated using (captain_id=(select auth.uid()));
create policy "captain_payouts_self" on public."captain_payouts" for select to authenticated using (captain_id=(select auth.uid()));
create policy "support_ticket_requester" on public."support_tickets" for select to authenticated using (raised_by_user_id=(select auth.uid()) or assigned_to=(select auth.uid()));
create policy "support_ticket_create" on public."support_tickets" for insert to authenticated with check (raised_by_user_id=(select auth.uid()));
create policy "support_message_access" on public."support_messages" for select to authenticated using (exists (select 1 from public.support_tickets t where t.id=ticket_id and (t.raised_by_user_id=(select auth.uid()) or t.assigned_to=(select auth.uid()))));
create policy "support_message_create" on public."support_messages" for insert to authenticated with check (sender_id=(select auth.uid()) and exists (select 1 from public.support_tickets t where t.id=ticket_id and (t.raised_by_user_id=(select auth.uid()) or t.assigned_to=(select auth.uid()))));
create policy "profiles_admin_read" on public."profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "profiles_admin_write" on public."profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "user_devices_admin_read" on public."user_devices" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "user_devices_admin_write" on public."user_devices" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "addresses_admin_read" on public."addresses" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "addresses_admin_write" on public."addresses" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "customer_profiles_admin_read" on public."customer_profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "customer_profiles_admin_write" on public."customer_profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "customer_preferences_admin_read" on public."customer_preferences" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "customer_preferences_admin_write" on public."customer_preferences" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_profiles_admin_read" on public."merchant_profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_profiles_admin_write" on public."merchant_profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_profiles_admin_read" on public."captain_profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_profiles_admin_write" on public."captain_profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "admin_profiles_admin_read" on public."admin_profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "admin_profiles_admin_write" on public."admin_profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "roles_admin_read" on public."roles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "roles_admin_write" on public."roles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "permissions_admin_read" on public."permissions" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "permissions_admin_write" on public."permissions" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "user_roles_admin_read" on public."user_roles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "user_roles_admin_write" on public."user_roles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "role_permissions_admin_read" on public."role_permissions" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "role_permissions_admin_write" on public."role_permissions" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shops_admin_read" on public."shops" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shops_admin_write" on public."shops" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_hours_admin_read" on public."shop_hours" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_hours_admin_write" on public."shop_hours" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_documents_admin_read" on public."shop_documents" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_documents_admin_write" on public."shop_documents" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_bank_accounts_admin_read" on public."shop_bank_accounts" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_bank_accounts_admin_write" on public."shop_bank_accounts" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "categories_admin_read" on public."categories" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "categories_admin_write" on public."categories" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "products_admin_read" on public."products" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "products_admin_write" on public."products" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "product_images_admin_read" on public."product_images" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "product_images_admin_write" on public."product_images" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "product_variants_admin_read" on public."product_variants" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "product_variants_admin_write" on public."product_variants" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "variant_barcodes_admin_read" on public."variant_barcodes" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "variant_barcodes_admin_write" on public."variant_barcodes" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "inventory_balances_admin_read" on public."inventory_balances" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "inventory_balances_admin_write" on public."inventory_balances" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "inventory_movements_admin_read" on public."inventory_movements" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "inventory_movements_admin_write" on public."inventory_movements" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "inventory_reservations_admin_read" on public."inventory_reservations" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "inventory_reservations_admin_write" on public."inventory_reservations" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "product_photo_matches_admin_read" on public."product_photo_matches" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "product_photo_matches_admin_write" on public."product_photo_matches" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_favourites_admin_read" on public."shop_favourites" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_favourites_admin_write" on public."shop_favourites" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "wishlist_items_admin_read" on public."wishlist_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "wishlist_items_admin_write" on public."wishlist_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_collections_admin_read" on public."shop_collections" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_collections_admin_write" on public."shop_collections" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "shop_collection_items_admin_read" on public."shop_collection_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "shop_collection_items_admin_write" on public."shop_collection_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "offers_admin_read" on public."offers" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "offers_admin_write" on public."offers" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "offer_products_admin_read" on public."offer_products" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "offer_products_admin_write" on public."offer_products" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "offer_redemptions_admin_read" on public."offer_redemptions" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "offer_redemptions_admin_write" on public."offer_redemptions" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "offline_sales_admin_read" on public."offline_sales" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "offline_sales_admin_write" on public."offline_sales" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "offline_sale_items_admin_read" on public."offline_sale_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "offline_sale_items_admin_write" on public."offline_sale_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "carts_admin_read" on public."carts" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "carts_admin_write" on public."carts" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "cart_items_admin_read" on public."cart_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "cart_items_admin_write" on public."cart_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "orders_admin_read" on public."orders" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "orders_admin_write" on public."orders" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "order_items_admin_read" on public."order_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "order_items_admin_write" on public."order_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "order_status_history_admin_read" on public."order_status_history" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "order_status_history_admin_write" on public."order_status_history" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_order_alerts_admin_read" on public."merchant_order_alerts" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_order_alerts_admin_write" on public."merchant_order_alerts" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_order_issues_admin_read" on public."merchant_order_issues" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_order_issues_admin_write" on public."merchant_order_issues" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "order_item_verifications_admin_read" on public."order_item_verifications" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "order_item_verifications_admin_write" on public."order_item_verifications" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "payments_admin_read" on public."payments" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "payments_admin_write" on public."payments" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "payment_events_admin_read" on public."payment_events" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "payment_events_admin_write" on public."payment_events" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "return_requests_admin_read" on public."return_requests" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "return_requests_admin_write" on public."return_requests" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "return_items_admin_read" on public."return_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "return_items_admin_write" on public."return_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "return_evidence_admin_read" on public."return_evidence" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "return_evidence_admin_write" on public."return_evidence" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "return_status_history_admin_read" on public."return_status_history" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "return_status_history_admin_write" on public."return_status_history" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "refunds_admin_read" on public."refunds" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "refunds_admin_write" on public."refunds" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_settlements_admin_read" on public."merchant_settlements" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_settlements_admin_write" on public."merchant_settlements" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_settlement_items_admin_read" on public."merchant_settlement_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_settlement_items_admin_write" on public."merchant_settlement_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_documents_admin_read" on public."captain_documents" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_documents_admin_write" on public."captain_documents" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "delivery_tasks_admin_read" on public."delivery_tasks" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "delivery_tasks_admin_write" on public."delivery_tasks" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "delivery_assignments_admin_read" on public."delivery_assignments" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "delivery_assignments_admin_write" on public."delivery_assignments" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_current_locations_admin_read" on public."captain_current_locations" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_current_locations_admin_write" on public."captain_current_locations" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_location_history_admin_read" on public."captain_location_history" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_location_history_admin_write" on public."captain_location_history" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "delivery_events_admin_read" on public."delivery_events" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "delivery_events_admin_write" on public."delivery_events" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "cod_collections_admin_read" on public."cod_collections" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "cod_collections_admin_write" on public."cod_collections" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_earnings_admin_read" on public."captain_earnings" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_earnings_admin_write" on public."captain_earnings" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_payouts_admin_read" on public."captain_payouts" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_payouts_admin_write" on public."captain_payouts" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "captain_payout_items_admin_read" on public."captain_payout_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "captain_payout_items_admin_write" on public."captain_payout_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_groups_admin_read" on public."style_groups" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_groups_admin_write" on public."style_groups" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_group_members_admin_read" on public."style_group_members" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_group_members_admin_write" on public."style_group_members" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_group_member_preferences_admin_read" on public."style_group_member_preferences" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_group_member_preferences_admin_write" on public."style_group_member_preferences" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_themes_admin_read" on public."style_themes" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_themes_admin_write" on public."style_themes" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_polls_admin_read" on public."style_polls" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_polls_admin_write" on public."style_polls" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_poll_options_admin_read" on public."style_poll_options" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_poll_options_admin_write" on public."style_poll_options" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_poll_votes_admin_read" on public."style_poll_votes" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_poll_votes_admin_write" on public."style_poll_votes" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_moodboards_admin_read" on public."style_moodboards" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_moodboards_admin_write" on public."style_moodboards" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_moodboard_items_admin_read" on public."style_moodboard_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_moodboard_items_admin_write" on public."style_moodboard_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "notifications_admin_read" on public."notifications" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "notifications_admin_write" on public."notifications" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "notification_deliveries_admin_read" on public."notification_deliveries" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "notification_deliveries_admin_write" on public."notification_deliveries" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "notification_preferences_admin_read" on public."notification_preferences" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "notification_preferences_admin_write" on public."notification_preferences" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "reviews_admin_read" on public."reviews" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "reviews_admin_write" on public."reviews" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "customer_events_admin_read" on public."customer_events" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "customer_events_admin_write" on public."customer_events" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "recommendation_sets_admin_read" on public."recommendation_sets" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "recommendation_sets_admin_write" on public."recommendation_sets" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "recommendation_items_admin_read" on public."recommendation_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "recommendation_items_admin_write" on public."recommendation_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "product_embeddings_admin_read" on public."product_embeddings" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "product_embeddings_admin_write" on public."product_embeddings" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "customer_embeddings_admin_read" on public."customer_embeddings" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "customer_embeddings_admin_write" on public."customer_embeddings" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "size_charts_admin_read" on public."size_charts" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "size_charts_admin_write" on public."size_charts" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "size_chart_measurements_admin_read" on public."size_chart_measurements" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "size_chart_measurements_admin_write" on public."size_chart_measurements" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "customer_body_profiles_admin_read" on public."customer_body_profiles" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "customer_body_profiles_admin_write" on public."customer_body_profiles" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "body_measurements_admin_read" on public."body_measurements" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "body_measurements_admin_write" on public."body_measurements" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "body_scan_sessions_admin_read" on public."body_scan_sessions" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "body_scan_sessions_admin_write" on public."body_scan_sessions" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "fit_recommendations_admin_read" on public."fit_recommendations" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "fit_recommendations_admin_write" on public."fit_recommendations" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "fit_feedback_admin_read" on public."fit_feedback" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "fit_feedback_admin_write" on public."fit_feedback" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "virtual_tryon_sessions_admin_read" on public."virtual_tryon_sessions" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "virtual_tryon_sessions_admin_write" on public."virtual_tryon_sessions" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "virtual_tryon_outputs_admin_read" on public."virtual_tryon_outputs" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "virtual_tryon_outputs_admin_write" on public."virtual_tryon_outputs" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_recommendation_sets_admin_read" on public."style_recommendation_sets" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_recommendation_sets_admin_write" on public."style_recommendation_sets" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "style_recommendation_items_admin_read" on public."style_recommendation_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "style_recommendation_items_admin_write" on public."style_recommendation_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "support_tickets_admin_read" on public."support_tickets" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "support_tickets_admin_write" on public."support_tickets" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "support_messages_admin_read" on public."support_messages" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "support_messages_admin_write" on public."support_messages" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "campaigns_admin_read" on public."campaigns" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "campaigns_admin_write" on public."campaigns" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "banners_admin_read" on public."banners" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "banners_admin_write" on public."banners" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "merchant_leads_admin_read" on public."merchant_leads" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "merchant_leads_admin_write" on public."merchant_leads" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "field_visits_admin_read" on public."field_visits" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "field_visits_admin_write" on public."field_visits" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "field_visit_checklist_items_admin_read" on public."field_visit_checklist_items" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "field_visit_checklist_items_admin_write" on public."field_visit_checklist_items" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "product_moderation_cases_admin_read" on public."product_moderation_cases" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "product_moderation_cases_admin_write" on public."product_moderation_cases" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "approval_requests_admin_read" on public."approval_requests" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "approval_requests_admin_write" on public."approval_requests" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "fraud_cases_admin_read" on public."fraud_cases" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "fraud_cases_admin_write" on public."fraud_cases" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "audit_logs_admin_read" on public."audit_logs" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "audit_logs_admin_write" on public."audit_logs" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "system_settings_admin_read" on public."system_settings" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "system_settings_admin_write" on public."system_settings" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
create policy "service_zones_admin_read" on public."service_zones" for select to authenticated using ((select private.has_permission('platform.read')));
create policy "service_zones_admin_write" on public."service_zones" for all to authenticated using ((select private.has_permission('platform.write'))) with check ((select private.has_permission('platform.write')));
