export const ADMIN_AUDIT_GATEWAY = Symbol('ADMIN_AUDIT_GATEWAY');
export const ADMIN_MERCHANT_GATEWAY = Symbol('ADMIN_MERCHANT_GATEWAY');
export const ADMIN_CAPTAIN_GATEWAY = Symbol('ADMIN_CAPTAIN_GATEWAY');
