export const ADMIN_AUDIT_GATEWAY = Symbol('ADMIN_AUDIT_GATEWAY');
export const ADMIN_ORDER_INVESTIGATION_GATEWAY = Symbol('ADMIN_ORDER_INVESTIGATION_GATEWAY');
export const ADMIN_ORDER_OPERATIONS_GATEWAY = Symbol('ADMIN_ORDER_OPERATIONS_GATEWAY');
