export const ADMIN_AUDIT_GATEWAY = Symbol('ADMIN_AUDIT_GATEWAY');
export const ADMIN_DASHBOARD_GATEWAY = Symbol('ADMIN_DASHBOARD_GATEWAY');
export const ADMIN_ORDER_INVESTIGATION_GATEWAY = Symbol('ADMIN_ORDER_INVESTIGATION_GATEWAY');
export const ADMIN_ORDER_OPERATIONS_GATEWAY = Symbol('ADMIN_ORDER_OPERATIONS_GATEWAY');
export const ADMIN_MERCHANT_GATEWAY = Symbol('ADMIN_MERCHANT_GATEWAY');
export const ADMIN_CAPTAIN_GATEWAY = Symbol('ADMIN_CAPTAIN_GATEWAY');
export const ADMIN_CONFIGURATION_GATEWAY = Symbol('ADMIN_CONFIGURATION_GATEWAY');
export const ADMIN_CASE_GATEWAY = Symbol('ADMIN_CASE_GATEWAY');
