export const CUSTOMER_PAYMENT_GATEWAY = Symbol('CUSTOMER_PAYMENT_GATEWAY');
export const PAYMENT_PROVIDER_GATEWAY = Symbol('PAYMENT_PROVIDER_GATEWAY');
export const PAYMENT_WEBHOOK_GATEWAY = Symbol('PAYMENT_WEBHOOK_GATEWAY');
export const PAYMENT_PROCESSING_GATEWAY = Symbol('PAYMENT_PROCESSING_GATEWAY');
