export const MERCHANT_ALERT_DELIVERY_CONFIGURATION = Symbol(
  'MERCHANT_ALERT_DELIVERY_CONFIGURATION',
);
export const MERCHANT_ALERT_DELIVERY_GATEWAY = Symbol('MERCHANT_ALERT_DELIVERY_GATEWAY');
export const MERCHANT_ALERT_SENDER = Symbol('MERCHANT_ALERT_SENDER');
export const FCM_ACCESS_TOKEN_PROVIDER = Symbol('FCM_ACCESS_TOKEN_PROVIDER');

export const MERCHANT_ALERT_SCHEDULER_GATEWAY = Symbol('MERCHANT_ALERT_SCHEDULER_GATEWAY');
